name: 'Read version with Build scripts'
description: 'Read the version of the assembly and retain'

runs:
  using: 'composite'
  steps:
    - name: 📥 Read version with Build scripts
      id: ver
      shell: bash
      run: |
        set -Eeuo pipefail
        nameBuild=$(go run github.com/amazing-generators/gometagen/cmd/gometagen@latest manifest get -source ./_run/values.yml -field name)
        versionBuild=$(go run github.com/amazing-generators/gometagen/cmd/gometagen@latest version print -source ./_run/values.yml)

        echo "BUILD_NAME=$nameBuild"   >  build_env.txt
        echo "BUILD_VER=$versionBuild" >> build_env.txt

        echo "name=$nameBuild"   >> $GITHUB_OUTPUT
        echo "version=$versionBuild" >> $GITHUB_OUTPUT

        echo "✔️ Found version: $versionBuild (Package Name: $nameBuild)"
