type: object
required: [ packageNames ]
properties:
  packageNames:
    type: array
    description: Composer package names available through this repository after collision resolution.
    example: [ vendor/package, vendor/utility ]
    items:
      type: string
      example: vendor/package
